LIST  P=16F628A ;MICROCONTROLADOR A USAR

INCLUDE <P16F628A.INC>   ;IMPORTAMOS LAS INTRUCCIONES DEL MICROCONTROLADOR

__CONFIG    _XT_OSC & _PWRTE_ON & _CP_OFF & _MCLRE_ON & _WDT_OFF       

ORG   0X00          ;INICIO DEL PROGRAMA    

BSF   STATUS,RP0    ;CAMBIAMOS AL BANCO 1
BSF   TRISA,RA0     ;RA0 ES ENTRADA
BSF   TRISA,RA3     ;RA3 REPRESENTA LA OTRA ENTRADA
BCF   TRISB,RB7     ;RB7 ES SALIDA 

BCF   STATUS,RP0    ;REGRESAMOS AL BANCO 0

BUCLE_PRINCIPAL
    BTFSC   PORTA, RA0   ; SI ESTA ENCENDIDO RA0
    GOTO    LED_ENCENDIDO
    BTFSS   PORTA, RA3   ; SI NO ESTÁ ENCENDIDO RA3
    GOTO    LED_APAGADO
    GOTO    LED_ENCENDIDO ; SI ESTÁ ENCENDIDO RA3, ENCENDER LED
LED_APAGADO
    BCF     PORTB, RB7   ; APAGAR LED
    GOTO    BUCLE_PRINCIPAL
LED_ENCENDIDO
    BSF     PORTB, RB7   ; ENCENDER LED
    GOTO    BUCLE_PRINCIPAL
END
