LIST  P=16F628A ;MICROCONTROLADOR A USAR
    
INCLUDE <P16F628A.INC>   ;IMPORTAMOS LAS INTRUCCIONES DEL MICROCONTROLADOR

__CONFIG    _XT_OSC & _PWRTE_ON & _CP_OFF & _MCLRE_ON & _WDT_OFF       

ORG   0X00          ;INICIO DEL PROGRAMA    
    
BSF   STATUS,RP0    ;CAMBIAMOS AL BANCO 1
BSF   TRISA,RA0     ;RAO ES ENTRADA
BSF   TRISA,RA3
BCF   TRISB,RB7     ;RB7 ES SALIDA 
    
BCF   STATUS,RP0    ;REGRESAMOS AL BANCO 0
    
    BUCLE_PRINCIPAL
    BTFSS  PORTA,RA0
    BTFSC  PORTA,RA0   ;SI ESTA ENCENDIDO RA0
    CALL   COMPROBAR_LED_2
    BCF    PORTB,RB7
    GOTO BUCLE_PRINCIPAL
    
    COMPROBAR_LED_2 
    BTFSC   PORTA,RA3     ;DEBE DE ESTAR EN 1
    BSF     PORTB,RB7     ;RB7 = 1
    BCF     PORTB,RB7     ;RB7 = 0
    RETURN
END  
